# Generated by Django 3.0.5 on 2020-05-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.IntegerField(default=101),
        ),
    ]
