# Generated by Django 3.0.5 on 2020-04-30 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('client_id', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='AssetsArchive',
            new_name='AssetArchive',
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
