# Generated by Django 3.0.5 on 2020-05-01 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200430_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetarchive',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
