# Generated by Django 3.0.5 on 2020-05-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200501_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetarchive',
            name='return_date',
            field=models.DateTimeField(default=None),
        ),
    ]
