# Generated by Django 3.0.5 on 2020-05-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200501_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetarchive',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
