# Generated by Django 3.0.5 on 2020-05-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetarchive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetarchive',
            name='status',
            field=models.CharField(blank=True, default='requested', max_length=20, null=True),
        ),
    ]
